# Generated by Django 4.2 on 2024-03-19 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='discription',
            new_name='userfrendly_name',
        ),
    ]
