# Generated by Django 4.2 on 2024-03-06 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_remove_product_is_favorite_favorites_is_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checked_Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_article', models.CharField(max_length=12, unique=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='fav',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.checked_favorites', to_field='fav_article'),
        ),
    ]
