# Generated by Django 4.2 on 2024-03-06 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_checked_favorites_product_fav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fav',
        ),
        migrations.DeleteModel(
            name='Checked_Favorites',
        ),
    ]
