# Generated by Django 4.2 on 2024-03-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_size_selected',
            field=models.BooleanField(default=False),
        ),
    ]
