# Generated by Django 4.2 on 2024-09-29 18:37

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='users_images'),
        ),
    ]
