# Generated by Django 4.2 on 2024-03-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_size_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_size_selected',
            field=models.BooleanField(default=True),
        ),
    ]
