# Generated by Django 4.2 on 2024-03-07 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_size_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_size_selected',
        ),
    ]
