# Generated by Django 4.2 on 2024-09-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cropping',
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users_images'),
        ),
    ]
