# Generated by Django 4.2 on 2024-10-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_cropping_alter_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='users_images')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
