volumes:
  static:
  media:
services:
  nmd:
    build:
      context: .
    ports:
      - '8000:8000'
    container_name: nmd_django
    env_file:
      - docker/env/.env
    volumes:
      - ./:/app
      - static:/app/static
      - media:/app/media
    command: sh -c "python manage.py collectstatic --no-input &&
                    python manage.py makemigrations &&
                    python manage.py migrate &&
                    gunicorn --workers=4 --reload --max-requests=1000 store.wsgi -b 0.0.0.0:8000"
  nginx:
    container_name: nginx
    working_dir: /app
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/app/static
      - media:/app/media
      - ./docker/nginx/:/etc/nginx/conf.d:ro
      - ./docker/certbot/conf:/etc/letsencrypt:ro
      - ./docker/certbot/www:/var/www/certbot:ro
    links:
      - nmd
    depends_on:
      - nmd

  certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./docker/certbot/conf:/etc/letsencrypt:rw
            - ./docker/certbot/www:/var/www/certbot:rw
#        command: certonly --webroot --webroot-path=/var/www/certbot/ --email efanovlex88@gmail.com --agree-tos --no-eff-email -d aefanov.online -d www.aefanov.online
        depends_on:
          - nginx